# Changes here will be overwritten by Copier
_commit: v0.15.1
_src_path: gh:KyleKing/my_go_template
author_email: dev.act.kyle@gmail.com
author_name: Kyle King
author_username: kyleking
copyright_date: '2026'
development_branch: main
module_path: github.com/KyleKing/djot-fmt
project_description: Automatic formatter for djot markup files
project_name: djot-fmt
project_type: cli
publish_python: true
repository_namespace: KyleKing
repository_provider: https://github.com
use_goreleaser: true

